import type { ModelData } from "./types"

// 模拟模型数据
export const modelData: Record<string, ModelData> = {
  "gemini-2-5-pro-preview": {
    id: "gemini-2-5-pro-preview",
    name: "Google: Gemini 2.5 Pro Preview",
    path: "google/gemini-2.5-pro-preview",
    created: "May 7, 2023",
    context: "1,048,576",
    inputPrice: "$1.25/M",
    outputPrice: "$10/M",
    imagePrice: "$5.16/K",
    categories: [
      { name: "Programming", count: 3 },
      { name: "Health", count: 4 },
      { name: "Academia", count: 4 },
      { name: "Legal", count: 6 },
      { name: "Marketing", count: 6 },
    ],
    description:
      'Gemini 2.5 Pro is Google\'s state-of-the-art AI model designed for advanced reasoning, coding, mathematics, and scientific tasks. It employs "thinking" capabilities, enabling it to reason through responses with enhanced accuracy and nuanced context handling. Gemini 2.5 Pro achieves top-tier performance across a wide range of benchmarks while maintaining efficient inference times.',
    providers: [
      {
        name: "Google AI Studio",
        context: "1.05M",
        maxOutput: "66K",
        inputPrice: "$1.25",
        inputPriceRange: "to $2.50",
        outputPrice: "$10",
        outputPriceRange: "to $15",
        latency: "16.46s",
        throughput: "352.9tps",
        uptime: 0.95,
        details: {
          dataPolicy: {
            promptTraining: "true",
            promptLogging: "Retained for unknown period",
            moderation: "Responsibility of developer",
          },
          supportedParameters: [
            "Max Tokens",
            "Temperature",
            "Top P",
            "Stop",
            "Frequency Penalty",
            "Presence Penalty",
            "Seed",
            "Top K",
            "Min P",
            "Repetition Penalty",
            "Logprobs",
            "Logit Bias",
            "Top Logprobs",
          ],
        },
      },
      {
        name: "Google Vertex",
        context: "1.05M",
        maxOutput: "66K",
        inputPrice: "$1.25",
        inputPriceRange: "to $2.50",
        outputPrice: "$10",
        outputPriceRange: "to $15",
        latency: "11.89s",
        throughput: "420.1tps",
        uptime: 0.98,
        details: {
          dataPolicy: {
            promptTraining: "false",
            promptLogging: "Retained for 30 days",
            moderation: "Responsibility of developer",
          },
          supportedParameters: [
            "Max Tokens",
            "Temperature",
            "Top P",
            "Stop",
            "Frequency Penalty",
            "Presence Penalty",
            "Seed",
            "Top K",
          ],
        },
      },
    ],
    throughputData: [
      { date: "Apr 1", google: 300, vertex: 350 },
      { date: "Apr 5", google: 500, vertex: 400 },
      { date: "Apr 10", google: 450, vertex: 300 },
      { date: "Apr 15", google: 470, vertex: 340 },
      { date: "Apr 20", google: 400, vertex: 380 },
      { date: "Apr 25", google: 480, vertex: 420 },
      { date: "May 1", google: 460, vertex: 400 },
    ],
    latencyData: [
      { date: "Apr 1", google: 18, vertex: 12 },
      { date: "Apr 5", google: 16, vertex: 11 },
      { date: "Apr 10", google: 17, vertex: 13 },
      { date: "Apr 15", google: 15, vertex: 12 },
      { date: "Apr 20", google: 16, vertex: 11 },
      { date: "Apr 25", google: 17, vertex: 12 },
      { date: "May 1", google: 16, vertex: 11 },
    ],
  },
  "claude-3-7-sonnet": {
    id: "claude-3-7-sonnet",
    name: "Anthropic: Claude 3.7 Sonnet",
    path: "anthropic/claude-3.7-sonnet",
    created: "June 15, 2023",
    context: "200,000",
    inputPrice: "$0.8/M",
    outputPrice: "$8/M",
    imagePrice: "$4.5/K",
    categories: [
      { name: "Programming", count: 4 },
      { name: "Health", count: 5 },
      { name: "Academia", count: 6 },
      { name: "Legal", count: 5 },
    ],
    description:
      "Claude 3.7 Sonnet is Anthropic's advanced large language model with improved reasoning capabilities, enhanced factual accuracy, and better instruction following. It excels at complex tasks while maintaining a balanced approach to safety and helpfulness.",
    providers: [
      {
        name: "Anthropic API",
        context: "200K",
        maxOutput: "50K",
        inputPrice: "$0.8",
        inputPriceRange: "to $1.5",
        outputPrice: "$8",
        outputPriceRange: "to $12",
        latency: "12.3s",
        throughput: "380.5tps",
        uptime: 0.99,
        details: {
          dataPolicy: {
            promptTraining: "false",
            promptLogging: "Retained for 30 days",
            moderation: "Built-in content filtering",
          },
          supportedParameters: ["Max Tokens", "Temperature", "Top P", "Stop", "Top K"],
        },
      },
    ],
    throughputData: [
      { date: "Apr 1", anthropic: 370 },
      { date: "Apr 5", anthropic: 390 },
      { date: "Apr 10", anthropic: 380 },
      { date: "Apr 15", anthropic: 400 },
      { date: "Apr 20", anthropic: 385 },
      { date: "Apr 25", anthropic: 395 },
      { date: "May 1", anthropic: 380 },
    ],
    latencyData: [
      { date: "Apr 1", anthropic: 13 },
      { date: "Apr 5", anthropic: 12 },
      { date: "Apr 10", anthropic: 12.5 },
      { date: "Apr 15", anthropic: 11.8 },
      { date: "Apr 20", anthropic: 12.2 },
      { date: "Apr 25", anthropic: 12.5 },
      { date: "May 1", anthropic: 12.3 },
    ],
  },
}
